---
# yamllint disable rule:line-length
name: Lint Code Base

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        if: ${{ !env.ACT }} # skip during local actions testing
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[lint]

      - name: Autoflake
        run: autoflake -c -r metis_client tests

      - name: Black
        run: black --check --diff metis_client tests

      - name: pyupgrade
        run: |
          find -name "*.py" -print0 | xargs -0 -n1 pyupgrade --py38-plus

      - name: isort
        run: isort -c --diff **/*.py

      - name: flake8
        run: |
          flake8 --exclude __init__.py
          flake8 --extend-ignore=F401

      - name: pylint
        run: pylint metis_client tests
